version: "3"
services:
  # Database
  database:
    image: postgres:12.2-alpine
    container_name: tu-todolist-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
